//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace clsHanaMES.wsReportMovementsHana {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsReportMovementsSoap", Namespace="http://tempuri.org/")]
    public partial class wsReportMovements : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Hana_GetMovementsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Hana_GetReportTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Movements_GetReportHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Movements_GetReportDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Movements_GetReportTotalCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback Mails_ListDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Hana_LastUpdateGRNsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_GetMailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_GetReportByMaterialTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_GetReportTotalsByMaterialTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_GetReportByMaterialGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_AdjustGetReportByMaterialGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_AdjustGetReportTotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Scrap_GetReportTotalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PNToAdjustByRecountOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_NoAdjusWhenRequiredOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PNCustomerToAdjutsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PNToCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_Mails_ListDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_Mails_GetHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_Mails_GetFooterOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback CycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidationMPN_GetMailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidationMPN_GetReportGrnNoValidatedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsReportMovements() {
            this.Url = global::clsHanaMES.Properties.Settings.Default.clsHanaMES_wsReportMovementsHana_wsReportMovements;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Hana_GetMovementsCompletedEventHandler Hana_GetMovementsCompleted;
        
        /// <remarks/>
        public event Hana_GetReportTestCompletedEventHandler Hana_GetReportTestCompleted;
        
        /// <remarks/>
        public event Movements_GetReportHeaderCompletedEventHandler Movements_GetReportHeaderCompleted;
        
        /// <remarks/>
        public event Movements_GetReportDetailsCompletedEventHandler Movements_GetReportDetailsCompleted;
        
        /// <remarks/>
        public event Movements_GetReportTotalCostCompletedEventHandler Movements_GetReportTotalCostCompleted;
        
        /// <remarks/>
        public event Mails_ListDistributionCompletedEventHandler Mails_ListDistributionCompleted;
        
        /// <remarks/>
        public event Hana_LastUpdateGRNsCompletedEventHandler Hana_LastUpdateGRNsCompleted;
        
        /// <remarks/>
        public event Scrap_GetMailListCompletedEventHandler Scrap_GetMailListCompleted;
        
        /// <remarks/>
        public event Scrap_GetReportByMaterialTypeCompletedEventHandler Scrap_GetReportByMaterialTypeCompleted;
        
        /// <remarks/>
        public event Scrap_GetReportTotalsByMaterialTypeCompletedEventHandler Scrap_GetReportTotalsByMaterialTypeCompleted;
        
        /// <remarks/>
        public event Scrap_GetReportByMaterialGroupCompletedEventHandler Scrap_GetReportByMaterialGroupCompleted;
        
        /// <remarks/>
        public event Scrap_AdjustGetReportByMaterialGroupCompletedEventHandler Scrap_AdjustGetReportByMaterialGroupCompleted;
        
        /// <remarks/>
        public event Scrap_AdjustGetReportTotalsCompletedEventHandler Scrap_AdjustGetReportTotalsCompleted;
        
        /// <remarks/>
        public event Scrap_GetReportTotalsCompletedEventHandler Scrap_GetReportTotalsCompleted;
        
        /// <remarks/>
        public event CycleCount_PNToAdjustByRecountCompletedEventHandler CycleCount_PNToAdjustByRecountCompleted;
        
        /// <remarks/>
        public event CycleCount_NoAdjusWhenRequiredCompletedEventHandler CycleCount_NoAdjusWhenRequiredCompleted;
        
        /// <remarks/>
        public event CycleCount_PNCustomerToAdjutsCompletedEventHandler CycleCount_PNCustomerToAdjutsCompleted;
        
        /// <remarks/>
        public event CycleCount_PNToCountCompletedEventHandler CycleCount_PNToCountCompleted;
        
        /// <remarks/>
        public event CycleCount_Mails_ListDistributionCompletedEventHandler CycleCount_Mails_ListDistributionCompleted;
        
        /// <remarks/>
        public event CycleCount_Mails_GetHeaderCompletedEventHandler CycleCount_Mails_GetHeaderCompleted;
        
        /// <remarks/>
        public event CycleCount_Mails_GetFooterCompletedEventHandler CycleCount_Mails_GetFooterCompleted;
        
        /// <remarks/>
        public event CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventHandler CycleCount_PeriodsNotifications_GetRecountPeriodCompleted;
        
        /// <remarks/>
        public event CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventHandler CycleCount_PeriodsNotifications_GetAnalysisPeriodCompleted;
        
        /// <remarks/>
        public event CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventHandler CycleCount_PeriodsNotifications_GetAdjustedPeriodCompleted;
        
        /// <remarks/>
        public event CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventHandler CycleCount_PeriodsNotifications_UpdateTotalPeriodCompleted;
        
        /// <remarks/>
        public event CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventHandler CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompleted;
        
        /// <remarks/>
        public event ValidationMPN_GetMailListCompletedEventHandler ValidationMPN_GetMailListCompleted;
        
        /// <remarks/>
        public event ValidationMPN_GetReportGrnNoValidatedCompletedEventHandler ValidationMPN_GetReportGrnNoValidatedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Hana_GetMovements", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Hana_GetMovements(string queryName) {
            object[] results = this.Invoke("Hana_GetMovements", new object[] {
                        queryName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Hana_GetMovementsAsync(string queryName) {
            this.Hana_GetMovementsAsync(queryName, null);
        }
        
        /// <remarks/>
        public void Hana_GetMovementsAsync(string queryName, object userState) {
            if ((this.Hana_GetMovementsOperationCompleted == null)) {
                this.Hana_GetMovementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHana_GetMovementsOperationCompleted);
            }
            this.InvokeAsync("Hana_GetMovements", new object[] {
                        queryName}, this.Hana_GetMovementsOperationCompleted, userState);
        }
        
        private void OnHana_GetMovementsOperationCompleted(object arg) {
            if ((this.Hana_GetMovementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Hana_GetMovementsCompleted(this, new Hana_GetMovementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Hana_GetReportTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Hana_GetReportTest(string Name, string Query) {
            object[] results = this.Invoke("Hana_GetReportTest", new object[] {
                        Name,
                        Query});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Hana_GetReportTestAsync(string Name, string Query) {
            this.Hana_GetReportTestAsync(Name, Query, null);
        }
        
        /// <remarks/>
        public void Hana_GetReportTestAsync(string Name, string Query, object userState) {
            if ((this.Hana_GetReportTestOperationCompleted == null)) {
                this.Hana_GetReportTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHana_GetReportTestOperationCompleted);
            }
            this.InvokeAsync("Hana_GetReportTest", new object[] {
                        Name,
                        Query}, this.Hana_GetReportTestOperationCompleted, userState);
        }
        
        private void OnHana_GetReportTestOperationCompleted(object arg) {
            if ((this.Hana_GetReportTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Hana_GetReportTestCompleted(this, new Hana_GetReportTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Movements_GetReportHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Movements_GetReportHeader() {
            object[] results = this.Invoke("Movements_GetReportHeader", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Movements_GetReportHeaderAsync() {
            this.Movements_GetReportHeaderAsync(null);
        }
        
        /// <remarks/>
        public void Movements_GetReportHeaderAsync(object userState) {
            if ((this.Movements_GetReportHeaderOperationCompleted == null)) {
                this.Movements_GetReportHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovements_GetReportHeaderOperationCompleted);
            }
            this.InvokeAsync("Movements_GetReportHeader", new object[0], this.Movements_GetReportHeaderOperationCompleted, userState);
        }
        
        private void OnMovements_GetReportHeaderOperationCompleted(object arg) {
            if ((this.Movements_GetReportHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Movements_GetReportHeaderCompleted(this, new Movements_GetReportHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Movements_GetReportDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Movements_GetReportDetails() {
            object[] results = this.Invoke("Movements_GetReportDetails", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Movements_GetReportDetailsAsync() {
            this.Movements_GetReportDetailsAsync(null);
        }
        
        /// <remarks/>
        public void Movements_GetReportDetailsAsync(object userState) {
            if ((this.Movements_GetReportDetailsOperationCompleted == null)) {
                this.Movements_GetReportDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovements_GetReportDetailsOperationCompleted);
            }
            this.InvokeAsync("Movements_GetReportDetails", new object[0], this.Movements_GetReportDetailsOperationCompleted, userState);
        }
        
        private void OnMovements_GetReportDetailsOperationCompleted(object arg) {
            if ((this.Movements_GetReportDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Movements_GetReportDetailsCompleted(this, new Movements_GetReportDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Movements_GetReportTotalCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Movements_GetReportTotalCost() {
            object[] results = this.Invoke("Movements_GetReportTotalCost", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Movements_GetReportTotalCostAsync() {
            this.Movements_GetReportTotalCostAsync(null);
        }
        
        /// <remarks/>
        public void Movements_GetReportTotalCostAsync(object userState) {
            if ((this.Movements_GetReportTotalCostOperationCompleted == null)) {
                this.Movements_GetReportTotalCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMovements_GetReportTotalCostOperationCompleted);
            }
            this.InvokeAsync("Movements_GetReportTotalCost", new object[0], this.Movements_GetReportTotalCostOperationCompleted, userState);
        }
        
        private void OnMovements_GetReportTotalCostOperationCompleted(object arg) {
            if ((this.Movements_GetReportTotalCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Movements_GetReportTotalCostCompleted(this, new Movements_GetReportTotalCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Mails_ListDistribution", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Mails_ListDistribution() {
            object[] results = this.Invoke("Mails_ListDistribution", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Mails_ListDistributionAsync() {
            this.Mails_ListDistributionAsync(null);
        }
        
        /// <remarks/>
        public void Mails_ListDistributionAsync(object userState) {
            if ((this.Mails_ListDistributionOperationCompleted == null)) {
                this.Mails_ListDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMails_ListDistributionOperationCompleted);
            }
            this.InvokeAsync("Mails_ListDistribution", new object[0], this.Mails_ListDistributionOperationCompleted, userState);
        }
        
        private void OnMails_ListDistributionOperationCompleted(object arg) {
            if ((this.Mails_ListDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Mails_ListDistributionCompleted(this, new Mails_ListDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Hana_LastUpdateGRNs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Hana_LastUpdateGRNs() {
            object[] results = this.Invoke("Hana_LastUpdateGRNs", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Hana_LastUpdateGRNsAsync() {
            this.Hana_LastUpdateGRNsAsync(null);
        }
        
        /// <remarks/>
        public void Hana_LastUpdateGRNsAsync(object userState) {
            if ((this.Hana_LastUpdateGRNsOperationCompleted == null)) {
                this.Hana_LastUpdateGRNsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHana_LastUpdateGRNsOperationCompleted);
            }
            this.InvokeAsync("Hana_LastUpdateGRNs", new object[0], this.Hana_LastUpdateGRNsOperationCompleted, userState);
        }
        
        private void OnHana_LastUpdateGRNsOperationCompleted(object arg) {
            if ((this.Hana_LastUpdateGRNsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Hana_LastUpdateGRNsCompleted(this, new Hana_LastUpdateGRNsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_GetMailList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Scrap_GetMailList() {
            object[] results = this.Invoke("Scrap_GetMailList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_GetMailListAsync() {
            this.Scrap_GetMailListAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_GetMailListAsync(object userState) {
            if ((this.Scrap_GetMailListOperationCompleted == null)) {
                this.Scrap_GetMailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_GetMailListOperationCompleted);
            }
            this.InvokeAsync("Scrap_GetMailList", new object[0], this.Scrap_GetMailListOperationCompleted, userState);
        }
        
        private void OnScrap_GetMailListOperationCompleted(object arg) {
            if ((this.Scrap_GetMailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_GetMailListCompleted(this, new Scrap_GetMailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_GetReportByMaterialType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_GetReportByMaterialType() {
            object[] results = this.Invoke("Scrap_GetReportByMaterialType", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_GetReportByMaterialTypeAsync() {
            this.Scrap_GetReportByMaterialTypeAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_GetReportByMaterialTypeAsync(object userState) {
            if ((this.Scrap_GetReportByMaterialTypeOperationCompleted == null)) {
                this.Scrap_GetReportByMaterialTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_GetReportByMaterialTypeOperationCompleted);
            }
            this.InvokeAsync("Scrap_GetReportByMaterialType", new object[0], this.Scrap_GetReportByMaterialTypeOperationCompleted, userState);
        }
        
        private void OnScrap_GetReportByMaterialTypeOperationCompleted(object arg) {
            if ((this.Scrap_GetReportByMaterialTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_GetReportByMaterialTypeCompleted(this, new Scrap_GetReportByMaterialTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_GetReportTotalsByMaterialType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_GetReportTotalsByMaterialType() {
            object[] results = this.Invoke("Scrap_GetReportTotalsByMaterialType", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_GetReportTotalsByMaterialTypeAsync() {
            this.Scrap_GetReportTotalsByMaterialTypeAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_GetReportTotalsByMaterialTypeAsync(object userState) {
            if ((this.Scrap_GetReportTotalsByMaterialTypeOperationCompleted == null)) {
                this.Scrap_GetReportTotalsByMaterialTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_GetReportTotalsByMaterialTypeOperationCompleted);
            }
            this.InvokeAsync("Scrap_GetReportTotalsByMaterialType", new object[0], this.Scrap_GetReportTotalsByMaterialTypeOperationCompleted, userState);
        }
        
        private void OnScrap_GetReportTotalsByMaterialTypeOperationCompleted(object arg) {
            if ((this.Scrap_GetReportTotalsByMaterialTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_GetReportTotalsByMaterialTypeCompleted(this, new Scrap_GetReportTotalsByMaterialTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_GetReportByMaterialGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_GetReportByMaterialGroup() {
            object[] results = this.Invoke("Scrap_GetReportByMaterialGroup", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_GetReportByMaterialGroupAsync() {
            this.Scrap_GetReportByMaterialGroupAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_GetReportByMaterialGroupAsync(object userState) {
            if ((this.Scrap_GetReportByMaterialGroupOperationCompleted == null)) {
                this.Scrap_GetReportByMaterialGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_GetReportByMaterialGroupOperationCompleted);
            }
            this.InvokeAsync("Scrap_GetReportByMaterialGroup", new object[0], this.Scrap_GetReportByMaterialGroupOperationCompleted, userState);
        }
        
        private void OnScrap_GetReportByMaterialGroupOperationCompleted(object arg) {
            if ((this.Scrap_GetReportByMaterialGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_GetReportByMaterialGroupCompleted(this, new Scrap_GetReportByMaterialGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_AdjustGetReportByMaterialGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_AdjustGetReportByMaterialGroup() {
            object[] results = this.Invoke("Scrap_AdjustGetReportByMaterialGroup", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_AdjustGetReportByMaterialGroupAsync() {
            this.Scrap_AdjustGetReportByMaterialGroupAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_AdjustGetReportByMaterialGroupAsync(object userState) {
            if ((this.Scrap_AdjustGetReportByMaterialGroupOperationCompleted == null)) {
                this.Scrap_AdjustGetReportByMaterialGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_AdjustGetReportByMaterialGroupOperationCompleted);
            }
            this.InvokeAsync("Scrap_AdjustGetReportByMaterialGroup", new object[0], this.Scrap_AdjustGetReportByMaterialGroupOperationCompleted, userState);
        }
        
        private void OnScrap_AdjustGetReportByMaterialGroupOperationCompleted(object arg) {
            if ((this.Scrap_AdjustGetReportByMaterialGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_AdjustGetReportByMaterialGroupCompleted(this, new Scrap_AdjustGetReportByMaterialGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_AdjustGetReportTotals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_AdjustGetReportTotals() {
            object[] results = this.Invoke("Scrap_AdjustGetReportTotals", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_AdjustGetReportTotalsAsync() {
            this.Scrap_AdjustGetReportTotalsAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_AdjustGetReportTotalsAsync(object userState) {
            if ((this.Scrap_AdjustGetReportTotalsOperationCompleted == null)) {
                this.Scrap_AdjustGetReportTotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_AdjustGetReportTotalsOperationCompleted);
            }
            this.InvokeAsync("Scrap_AdjustGetReportTotals", new object[0], this.Scrap_AdjustGetReportTotalsOperationCompleted, userState);
        }
        
        private void OnScrap_AdjustGetReportTotalsOperationCompleted(object arg) {
            if ((this.Scrap_AdjustGetReportTotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_AdjustGetReportTotalsCompleted(this, new Scrap_AdjustGetReportTotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Scrap_GetReportTotals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Scrap_GetReportTotals() {
            object[] results = this.Invoke("Scrap_GetReportTotals", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Scrap_GetReportTotalsAsync() {
            this.Scrap_GetReportTotalsAsync(null);
        }
        
        /// <remarks/>
        public void Scrap_GetReportTotalsAsync(object userState) {
            if ((this.Scrap_GetReportTotalsOperationCompleted == null)) {
                this.Scrap_GetReportTotalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScrap_GetReportTotalsOperationCompleted);
            }
            this.InvokeAsync("Scrap_GetReportTotals", new object[0], this.Scrap_GetReportTotalsOperationCompleted, userState);
        }
        
        private void OnScrap_GetReportTotalsOperationCompleted(object arg) {
            if ((this.Scrap_GetReportTotalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Scrap_GetReportTotalsCompleted(this, new Scrap_GetReportTotalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PNToAdjustByRecount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PNToAdjustByRecount(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_PNToAdjustByRecount", new object[] {
                        PKCustomer});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PNToAdjustByRecountAsync(int PKCustomer) {
            this.CycleCount_PNToAdjustByRecountAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_PNToAdjustByRecountAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_PNToAdjustByRecountOperationCompleted == null)) {
                this.CycleCount_PNToAdjustByRecountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PNToAdjustByRecountOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PNToAdjustByRecount", new object[] {
                        PKCustomer}, this.CycleCount_PNToAdjustByRecountOperationCompleted, userState);
        }
        
        private void OnCycleCount_PNToAdjustByRecountOperationCompleted(object arg) {
            if ((this.CycleCount_PNToAdjustByRecountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PNToAdjustByRecountCompleted(this, new CycleCount_PNToAdjustByRecountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_NoAdjusWhenRequired", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_NoAdjusWhenRequired(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_NoAdjusWhenRequired", new object[] {
                        PKCustomer});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_NoAdjusWhenRequiredAsync(int PKCustomer) {
            this.CycleCount_NoAdjusWhenRequiredAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_NoAdjusWhenRequiredAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_NoAdjusWhenRequiredOperationCompleted == null)) {
                this.CycleCount_NoAdjusWhenRequiredOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_NoAdjusWhenRequiredOperationCompleted);
            }
            this.InvokeAsync("CycleCount_NoAdjusWhenRequired", new object[] {
                        PKCustomer}, this.CycleCount_NoAdjusWhenRequiredOperationCompleted, userState);
        }
        
        private void OnCycleCount_NoAdjusWhenRequiredOperationCompleted(object arg) {
            if ((this.CycleCount_NoAdjusWhenRequiredCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_NoAdjusWhenRequiredCompleted(this, new CycleCount_NoAdjusWhenRequiredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PNCustomerToAdjuts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PNCustomerToAdjuts(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_PNCustomerToAdjuts", new object[] {
                        PKCustomer});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PNCustomerToAdjutsAsync(int PKCustomer) {
            this.CycleCount_PNCustomerToAdjutsAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_PNCustomerToAdjutsAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_PNCustomerToAdjutsOperationCompleted == null)) {
                this.CycleCount_PNCustomerToAdjutsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PNCustomerToAdjutsOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PNCustomerToAdjuts", new object[] {
                        PKCustomer}, this.CycleCount_PNCustomerToAdjutsOperationCompleted, userState);
        }
        
        private void OnCycleCount_PNCustomerToAdjutsOperationCompleted(object arg) {
            if ((this.CycleCount_PNCustomerToAdjutsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PNCustomerToAdjutsCompleted(this, new CycleCount_PNCustomerToAdjutsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PNToCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PNToCount(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_PNToCount", new object[] {
                        PKCustomer});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PNToCountAsync(int PKCustomer) {
            this.CycleCount_PNToCountAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_PNToCountAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_PNToCountOperationCompleted == null)) {
                this.CycleCount_PNToCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PNToCountOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PNToCount", new object[] {
                        PKCustomer}, this.CycleCount_PNToCountOperationCompleted, userState);
        }
        
        private void OnCycleCount_PNToCountOperationCompleted(object arg) {
            if ((this.CycleCount_PNToCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PNToCountCompleted(this, new CycleCount_PNToCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_Mails_ListDistribution", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CycleCount_Mails_ListDistribution(int PKCustomer, int Level) {
            object[] results = this.Invoke("CycleCount_Mails_ListDistribution", new object[] {
                        PKCustomer,
                        Level});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_Mails_ListDistributionAsync(int PKCustomer, int Level) {
            this.CycleCount_Mails_ListDistributionAsync(PKCustomer, Level, null);
        }
        
        /// <remarks/>
        public void CycleCount_Mails_ListDistributionAsync(int PKCustomer, int Level, object userState) {
            if ((this.CycleCount_Mails_ListDistributionOperationCompleted == null)) {
                this.CycleCount_Mails_ListDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_Mails_ListDistributionOperationCompleted);
            }
            this.InvokeAsync("CycleCount_Mails_ListDistribution", new object[] {
                        PKCustomer,
                        Level}, this.CycleCount_Mails_ListDistributionOperationCompleted, userState);
        }
        
        private void OnCycleCount_Mails_ListDistributionOperationCompleted(object arg) {
            if ((this.CycleCount_Mails_ListDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_Mails_ListDistributionCompleted(this, new CycleCount_Mails_ListDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_Mails_GetHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CycleCount_Mails_GetHeader() {
            object[] results = this.Invoke("CycleCount_Mails_GetHeader", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_Mails_GetHeaderAsync() {
            this.CycleCount_Mails_GetHeaderAsync(null);
        }
        
        /// <remarks/>
        public void CycleCount_Mails_GetHeaderAsync(object userState) {
            if ((this.CycleCount_Mails_GetHeaderOperationCompleted == null)) {
                this.CycleCount_Mails_GetHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_Mails_GetHeaderOperationCompleted);
            }
            this.InvokeAsync("CycleCount_Mails_GetHeader", new object[0], this.CycleCount_Mails_GetHeaderOperationCompleted, userState);
        }
        
        private void OnCycleCount_Mails_GetHeaderOperationCompleted(object arg) {
            if ((this.CycleCount_Mails_GetHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_Mails_GetHeaderCompleted(this, new CycleCount_Mails_GetHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_Mails_GetFooter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CycleCount_Mails_GetFooter() {
            object[] results = this.Invoke("CycleCount_Mails_GetFooter", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_Mails_GetFooterAsync() {
            this.CycleCount_Mails_GetFooterAsync(null);
        }
        
        /// <remarks/>
        public void CycleCount_Mails_GetFooterAsync(object userState) {
            if ((this.CycleCount_Mails_GetFooterOperationCompleted == null)) {
                this.CycleCount_Mails_GetFooterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_Mails_GetFooterOperationCompleted);
            }
            this.InvokeAsync("CycleCount_Mails_GetFooter", new object[0], this.CycleCount_Mails_GetFooterOperationCompleted, userState);
        }
        
        private void OnCycleCount_Mails_GetFooterOperationCompleted(object arg) {
            if ((this.CycleCount_Mails_GetFooterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_Mails_GetFooterCompleted(this, new CycleCount_Mails_GetFooterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PeriodsNotifications_GetRecountPeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PeriodsNotifications_GetRecountPeriod(int PKCustomer, int LevelEscalation) {
            object[] results = this.Invoke("CycleCount_PeriodsNotifications_GetRecountPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetRecountPeriodAsync(int PKCustomer, int LevelEscalation) {
            this.CycleCount_PeriodsNotifications_GetRecountPeriodAsync(PKCustomer, LevelEscalation, null);
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetRecountPeriodAsync(int PKCustomer, int LevelEscalation, object userState) {
            if ((this.CycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted == null)) {
                this.CycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PeriodsNotifications_GetRecountPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation}, this.CycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted, userState);
        }
        
        private void OnCycleCount_PeriodsNotifications_GetRecountPeriodOperationCompleted(object arg) {
            if ((this.CycleCount_PeriodsNotifications_GetRecountPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PeriodsNotifications_GetRecountPeriodCompleted(this, new CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PeriodsNotifications_GetAnalysisPeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PeriodsNotifications_GetAnalysisPeriod(int PKCustomer, int LevelEscalation) {
            object[] results = this.Invoke("CycleCount_PeriodsNotifications_GetAnalysisPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetAnalysisPeriodAsync(int PKCustomer, int LevelEscalation) {
            this.CycleCount_PeriodsNotifications_GetAnalysisPeriodAsync(PKCustomer, LevelEscalation, null);
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetAnalysisPeriodAsync(int PKCustomer, int LevelEscalation, object userState) {
            if ((this.CycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted == null)) {
                this.CycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PeriodsNotifications_GetAnalysisPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation}, this.CycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted, userState);
        }
        
        private void OnCycleCount_PeriodsNotifications_GetAnalysisPeriodOperationCompleted(object arg) {
            if ((this.CycleCount_PeriodsNotifications_GetAnalysisPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PeriodsNotifications_GetAnalysisPeriodCompleted(this, new CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PeriodsNotifications_GetAdjustedPeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CycleCount_PeriodsNotifications_GetAdjustedPeriod(int PKCustomer, int LevelEscalation) {
            object[] results = this.Invoke("CycleCount_PeriodsNotifications_GetAdjustedPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetAdjustedPeriodAsync(int PKCustomer, int LevelEscalation) {
            this.CycleCount_PeriodsNotifications_GetAdjustedPeriodAsync(PKCustomer, LevelEscalation, null);
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_GetAdjustedPeriodAsync(int PKCustomer, int LevelEscalation, object userState) {
            if ((this.CycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted == null)) {
                this.CycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PeriodsNotifications_GetAdjustedPeriod", new object[] {
                        PKCustomer,
                        LevelEscalation}, this.CycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted, userState);
        }
        
        private void OnCycleCount_PeriodsNotifications_GetAdjustedPeriodOperationCompleted(object arg) {
            if ((this.CycleCount_PeriodsNotifications_GetAdjustedPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PeriodsNotifications_GetAdjustedPeriodCompleted(this, new CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PeriodsNotifications_UpdateTotalPeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CycleCount_PeriodsNotifications_UpdateTotalPeriod(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_PeriodsNotifications_UpdateTotalPeriod", new object[] {
                        PKCustomer});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_UpdateTotalPeriodAsync(int PKCustomer) {
            this.CycleCount_PeriodsNotifications_UpdateTotalPeriodAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_UpdateTotalPeriodAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted == null)) {
                this.CycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PeriodsNotifications_UpdateTotalPeriod", new object[] {
                        PKCustomer}, this.CycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted, userState);
        }
        
        private void OnCycleCount_PeriodsNotifications_UpdateTotalPeriodOperationCompleted(object arg) {
            if ((this.CycleCount_PeriodsNotifications_UpdateTotalPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PeriodsNotifications_UpdateTotalPeriodCompleted(this, new CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CycleCount_PeriodsNotifications_UpdateStatusPNPeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CycleCount_PeriodsNotifications_UpdateStatusPNPeriod(int PKCustomer) {
            object[] results = this.Invoke("CycleCount_PeriodsNotifications_UpdateStatusPNPeriod", new object[] {
                        PKCustomer});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_UpdateStatusPNPeriodAsync(int PKCustomer) {
            this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodAsync(PKCustomer, null);
        }
        
        /// <remarks/>
        public void CycleCount_PeriodsNotifications_UpdateStatusPNPeriodAsync(int PKCustomer, object userState) {
            if ((this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted == null)) {
                this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted);
            }
            this.InvokeAsync("CycleCount_PeriodsNotifications_UpdateStatusPNPeriod", new object[] {
                        PKCustomer}, this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted, userState);
        }
        
        private void OnCycleCount_PeriodsNotifications_UpdateStatusPNPeriodOperationCompleted(object arg) {
            if ((this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompleted(this, new CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidationMPN_GetMailList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidationMPN_GetMailList() {
            object[] results = this.Invoke("ValidationMPN_GetMailList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidationMPN_GetMailListAsync() {
            this.ValidationMPN_GetMailListAsync(null);
        }
        
        /// <remarks/>
        public void ValidationMPN_GetMailListAsync(object userState) {
            if ((this.ValidationMPN_GetMailListOperationCompleted == null)) {
                this.ValidationMPN_GetMailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidationMPN_GetMailListOperationCompleted);
            }
            this.InvokeAsync("ValidationMPN_GetMailList", new object[0], this.ValidationMPN_GetMailListOperationCompleted, userState);
        }
        
        private void OnValidationMPN_GetMailListOperationCompleted(object arg) {
            if ((this.ValidationMPN_GetMailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidationMPN_GetMailListCompleted(this, new ValidationMPN_GetMailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidationMPN_GetReportGrnNoValidated", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ValidationMPN_GetReportGrnNoValidated() {
            object[] results = this.Invoke("ValidationMPN_GetReportGrnNoValidated", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ValidationMPN_GetReportGrnNoValidatedAsync() {
            this.ValidationMPN_GetReportGrnNoValidatedAsync(null);
        }
        
        /// <remarks/>
        public void ValidationMPN_GetReportGrnNoValidatedAsync(object userState) {
            if ((this.ValidationMPN_GetReportGrnNoValidatedOperationCompleted == null)) {
                this.ValidationMPN_GetReportGrnNoValidatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidationMPN_GetReportGrnNoValidatedOperationCompleted);
            }
            this.InvokeAsync("ValidationMPN_GetReportGrnNoValidated", new object[0], this.ValidationMPN_GetReportGrnNoValidatedOperationCompleted, userState);
        }
        
        private void OnValidationMPN_GetReportGrnNoValidatedOperationCompleted(object arg) {
            if ((this.ValidationMPN_GetReportGrnNoValidatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidationMPN_GetReportGrnNoValidatedCompleted(this, new ValidationMPN_GetReportGrnNoValidatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Hana_GetMovementsCompletedEventHandler(object sender, Hana_GetMovementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hana_GetMovementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Hana_GetMovementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Hana_GetReportTestCompletedEventHandler(object sender, Hana_GetReportTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hana_GetReportTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Hana_GetReportTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Movements_GetReportHeaderCompletedEventHandler(object sender, Movements_GetReportHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Movements_GetReportHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Movements_GetReportHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Movements_GetReportDetailsCompletedEventHandler(object sender, Movements_GetReportDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Movements_GetReportDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Movements_GetReportDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Movements_GetReportTotalCostCompletedEventHandler(object sender, Movements_GetReportTotalCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Movements_GetReportTotalCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Movements_GetReportTotalCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Mails_ListDistributionCompletedEventHandler(object sender, Mails_ListDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mails_ListDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Mails_ListDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Hana_LastUpdateGRNsCompletedEventHandler(object sender, Hana_LastUpdateGRNsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hana_LastUpdateGRNsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Hana_LastUpdateGRNsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_GetMailListCompletedEventHandler(object sender, Scrap_GetMailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_GetMailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_GetMailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_GetReportByMaterialTypeCompletedEventHandler(object sender, Scrap_GetReportByMaterialTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_GetReportByMaterialTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_GetReportByMaterialTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_GetReportTotalsByMaterialTypeCompletedEventHandler(object sender, Scrap_GetReportTotalsByMaterialTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_GetReportTotalsByMaterialTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_GetReportTotalsByMaterialTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_GetReportByMaterialGroupCompletedEventHandler(object sender, Scrap_GetReportByMaterialGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_GetReportByMaterialGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_GetReportByMaterialGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_AdjustGetReportByMaterialGroupCompletedEventHandler(object sender, Scrap_AdjustGetReportByMaterialGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_AdjustGetReportByMaterialGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_AdjustGetReportByMaterialGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_AdjustGetReportTotalsCompletedEventHandler(object sender, Scrap_AdjustGetReportTotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_AdjustGetReportTotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_AdjustGetReportTotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void Scrap_GetReportTotalsCompletedEventHandler(object sender, Scrap_GetReportTotalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Scrap_GetReportTotalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Scrap_GetReportTotalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PNToAdjustByRecountCompletedEventHandler(object sender, CycleCount_PNToAdjustByRecountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PNToAdjustByRecountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PNToAdjustByRecountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_NoAdjusWhenRequiredCompletedEventHandler(object sender, CycleCount_NoAdjusWhenRequiredCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_NoAdjusWhenRequiredCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_NoAdjusWhenRequiredCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PNCustomerToAdjutsCompletedEventHandler(object sender, CycleCount_PNCustomerToAdjutsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PNCustomerToAdjutsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PNCustomerToAdjutsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PNToCountCompletedEventHandler(object sender, CycleCount_PNToCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PNToCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PNToCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_Mails_ListDistributionCompletedEventHandler(object sender, CycleCount_Mails_ListDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_Mails_ListDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_Mails_ListDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_Mails_GetHeaderCompletedEventHandler(object sender, CycleCount_Mails_GetHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_Mails_GetHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_Mails_GetHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_Mails_GetFooterCompletedEventHandler(object sender, CycleCount_Mails_GetFooterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_Mails_GetFooterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_Mails_GetFooterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventHandler(object sender, CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PeriodsNotifications_GetRecountPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventHandler(object sender, CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PeriodsNotifications_GetAnalysisPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventHandler(object sender, CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PeriodsNotifications_GetAdjustedPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventHandler(object sender, CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PeriodsNotifications_UpdateTotalPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventHandler(object sender, CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CycleCount_PeriodsNotifications_UpdateStatusPNPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void ValidationMPN_GetMailListCompletedEventHandler(object sender, ValidationMPN_GetMailListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidationMPN_GetMailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidationMPN_GetMailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void ValidationMPN_GetReportGrnNoValidatedCompletedEventHandler(object sender, ValidationMPN_GetReportGrnNoValidatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidationMPN_GetReportGrnNoValidatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidationMPN_GetReportGrnNoValidatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591